# Generated by Django 5.1.3 on 2025-01-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
