# Generated by Django 5.1.3 on 2025-01-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='address_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='position_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='position_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_src_az',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_src_en',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_src_ru',
            field=models.URLField(null=True),
        ),
    ]
