# Generated by Django 5.1.3 on 2025-01-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_banner_description_az_banner_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_az',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_az',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_src_az',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_src_en',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_src_ru',
        ),
    ]
