# Generated by Django 5.1.3 on 2024-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('breadcrumb_title', models.CharField(max_length=255)),
                ('breadcrumb_home', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='backgrounds_service/')),
            ],
            options={
                'verbose_name': '(Service seifesi 1 )',
                'verbose_name_plural': '(Service seifesi 1)',
            },
        ),
    ]
