# Generated by Django 5.1.3 on 2024-12-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreFeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': '(Service seifesi 3  )', 'verbose_name_plural': '(Service seifesi 3)'},
        ),
        migrations.CreateModel(
            name='CoreFeatureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.corefeature')),
            ],
        ),
    ]
