# Generated by Django 5.1.3 on 2024-12-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_corefeature_corefeaturesection_alter_counter_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreFeatureSection',
        ),
    ]
