# Generated by Django 5.1.3 on 2024-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_delete_corefeaturesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='video-popup-images/')),
                ('video_file', models.FileField(upload_to='video-popup-videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='corefeaturevideo',
            name='feature',
        ),
        migrations.DeleteModel(
            name='CoreFeature',
        ),
        migrations.DeleteModel(
            name='CoreFeatureVideo',
        ),
    ]
