# Generated by Django 5.1.3 on 2025-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceicon',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceicon',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceicon',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceicon',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceicon',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceicon',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='breadcrumb_home_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='breadcrumb_home_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='breadcrumb_home_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='breadcrumb_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='breadcrumb_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='breadcrumb_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videopopup',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videopopup',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videopopup',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
