# Generated by Django 5.1.3 on 2025-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_counter_description_az_counter_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_text', models.TextField()),
                ('information_text_az', models.TextField(null=True)),
                ('information_text_en', models.TextField(null=True)),
                ('information_text_ru', models.TextField(null=True)),
                ('address', models.TextField()),
                ('address_az', models.TextField(null=True)),
                ('address_en', models.TextField(null=True)),
                ('address_ru', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_az', models.CharField(max_length=20, null=True)),
                ('phone_en', models.CharField(max_length=20, null=True)),
                ('phone_ru', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_az', models.EmailField(max_length=254, null=True)),
                ('email_en', models.EmailField(max_length=254, null=True)),
                ('email_ru', models.EmailField(max_length=254, null=True)),
                ('newsletter_text', models.TextField()),
                ('newsletter_text_az', models.TextField(null=True)),
                ('newsletter_text_en', models.TextField(null=True)),
                ('newsletter_text_ru', models.TextField(null=True)),
            ],
        ),
    ]
