# Generated by Django 5.1.3 on 2024-12-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Şəkil')),
                ('button_text', models.CharField(default='Daha çox', max_length=100, verbose_name='Düymə mətni')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Düymə keçidi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra nömrəsi')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ['order'],
            },
        ),
    ]
