# Generated by Django 5.1.3 on 2024-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_slider_button_link_remove_slider_button_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='order',
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider_images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
