# Generated by Django 5.1.3 on 2024-12-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_homeservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='icon',
        ),
        migrations.AddField(
            model_name='homeservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
