# Generated by Django 5.1.3 on 2024-12-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_homeservice_icon_homeservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
