# Generated by Django 5.1.3 on 2024-12-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
