# Generated by Django 5.1.3 on 2024-12-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreFeatureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
