# Generated by Django 5.1.3 on 2024-12-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
