# Generated by Django 5.1.3 on 2024-12-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_partners_delete_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
