# Generated by Django 5.1.3 on 2024-12-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_delete_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenovationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='background_images/')),
                ('circle_image', models.ImageField(upload_to='circle_images/')),
            ],
        ),
    ]
