# Generated by Django 5.1.3 on 2024-12-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_clientreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreview',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='clientreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_review_images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='reviews_header',
            field=models.CharField(default='Our Clients’ Feedback', max_length=255),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='section_header',
            field=models.CharField(default='Client Reviews', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
