# Generated by Django 5.1.3 on 2024-12-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_remove_clientreview_profile_image_clientreview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='reviews_header',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='section_header',
            field=models.CharField(max_length=255),
        ),
    ]
