# Generated by Django 5.1.3 on 2024-12-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_clientreview_reviews_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('breadcrumb_title', models.CharField(max_length=255)),
                ('breadcrumb_home', models.CharField(max_length=255)),
                ('background_image', models.ImageField(default='backgrounds/default.png', upload_to='backgrounds/')),
            ],
        ),
    ]
