# Generated by Django 5.1.3 on 2024-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(default='team_images/default.jpg', upload_to='team_images/')),
            ],
            options={
                'verbose_name': 'About seifesi 2',
                'verbose_name_plural': 'About seifesi 2',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About (About seifesi 1 )', 'verbose_name_plural': 'About (About seifesi 1)'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='breadcrumb_home',
            field=models.CharField(default='Home', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='breadcrumb_title',
            field=models.CharField(default='About Us', max_length=255),
        ),
    ]
