# Generated by Django 5.1.3 on 2024-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_team_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=255)),
                ('who_we_are_text', models.TextField()),
                ('who_we_are_image', models.ImageField(upload_to='about_images/')),
                ('whats_in_it_for_me_title', models.CharField(max_length=255)),
                ('whats_in_it_for_me_points', models.JSONField()),
                ('whats_in_it_for_me_image', models.ImageField(upload_to='about_images/')),
            ],
            options={
                'verbose_name': 'About seifesi 2',
                'verbose_name_plural': 'About seifesi 2',
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
