# Generated by Django 5.1.3 on 2024-12-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_aboutsection_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About seifesi 3',
                'verbose_name_plural': 'About seifesi 3',
                'ordering': ['step_number'],
            },
        ),
    ]
