# Generated by Django 5.1.3 on 2024-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_howitworksstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
                ('heading_icon', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
                ('heading_text', models.CharField(default='Plan + Control', max_length=255)),
                ('heading_title', models.CharField(default='How it Works', max_length=255)),
                ('step_1_title', models.CharField(default='Phase Plan', max_length=255)),
                ('step_1_description', models.TextField(default='This step connects the design process and its milestones with construction.')),
                ('step_2_title', models.CharField(default='Design Pull Plan', max_length=255)),
                ('step_2_description', models.TextField(default='We work with the design team to establish a detailed plan for reaching our goals.')),
                ('step_3_title', models.CharField(default='Coordinated Layout', max_length=255)),
                ('step_3_description', models.TextField(default='This process creates a single point of truth: drawings all project.')),
                ('step_4_title', models.CharField(default='Quality Control', max_length=255)),
                ('step_4_description', models.TextField(default='Having geometry worked out in the Layout step, prior to construction.')),
            ],
            options={
                'verbose_name': 'About seifesi 3',
                'verbose_name_plural': 'About seifesi 3',
            },
        ),
        migrations.DeleteModel(
            name='HowItWorksStep',
        ),
    ]
