# Generated by Django 5.1.3 on 2024-12-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_howitworks_delete_howitworksstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howitworks',
            name='heading_icon',
        ),
    ]
