# Generated by Django 5.1.3 on 2025-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_remove_howitworks_heading_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_heading_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_heading_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='whats_in_it_for_me_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='whats_in_it_for_me_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='whats_in_it_for_me_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='who_we_are_text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='who_we_are_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='who_we_are_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home_az',
            field=models.CharField(default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home_en',
            field=models.CharField(default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home_ru',
            field=models.CharField(default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title_az',
            field=models.CharField(default='About Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title_en',
            field=models.CharField(default='About Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title_ru',
            field=models.CharField(default='About Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='position_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='position_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='position_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='review_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='reviews_header_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='reviews_header_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='reviews_header_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='section_header_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='section_header_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='section_header_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeature',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corefeature',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corefeature',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corefeature',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeature',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeature',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturesection',
            name='subtitle_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturesection',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturesection',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturesection',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturesection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturesection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corefeaturevideo',
            name='thumbnail_az',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='corefeaturevideo',
            name='thumbnail_en',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='corefeaturevideo',
            name='thumbnail_ru',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='corefeaturevideo',
            name='video_file_az',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='corefeaturevideo',
            name='video_file_en',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='corefeaturevideo',
            name='video_file_ru',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='counter',
            name='description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='heading_text_az',
            field=models.CharField(default='Plan + Control', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='heading_text_en',
            field=models.CharField(default='Plan + Control', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='heading_text_ru',
            field=models.CharField(default='Plan + Control', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='heading_title_az',
            field=models.CharField(default='How it Works', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='heading_title_en',
            field=models.CharField(default='How it Works', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='heading_title_ru',
            field=models.CharField(default='How it Works', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_1_description_az',
            field=models.TextField(default='This step connects the design process and its milestones with construction.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_1_description_en',
            field=models.TextField(default='This step connects the design process and its milestones with construction.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_1_description_ru',
            field=models.TextField(default='This step connects the design process and its milestones with construction.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_1_title_az',
            field=models.CharField(default='Phase Plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_1_title_en',
            field=models.CharField(default='Phase Plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_1_title_ru',
            field=models.CharField(default='Phase Plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_2_description_az',
            field=models.TextField(default='We work with the design team to establish a detailed plan for reaching our goals.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_2_description_en',
            field=models.TextField(default='We work with the design team to establish a detailed plan for reaching our goals.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_2_description_ru',
            field=models.TextField(default='We work with the design team to establish a detailed plan for reaching our goals.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_2_title_az',
            field=models.CharField(default='Design Pull Plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_2_title_en',
            field=models.CharField(default='Design Pull Plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_2_title_ru',
            field=models.CharField(default='Design Pull Plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_3_description_az',
            field=models.TextField(default='This process creates a single point of truth: drawings all project.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_3_description_en',
            field=models.TextField(default='This process creates a single point of truth: drawings all project.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_3_description_ru',
            field=models.TextField(default='This process creates a single point of truth: drawings all project.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_3_title_az',
            field=models.CharField(default='Coordinated Layout', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_3_title_en',
            field=models.CharField(default='Coordinated Layout', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_3_title_ru',
            field=models.CharField(default='Coordinated Layout', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_4_description_az',
            field=models.TextField(default='Having geometry worked out in the Layout step, prior to construction.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_4_description_en',
            field=models.TextField(default='Having geometry worked out in the Layout step, prior to construction.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_4_description_ru',
            field=models.TextField(default='Having geometry worked out in the Layout step, prior to construction.', null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_4_title_az',
            field=models.CharField(default='Quality Control', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_4_title_en',
            field=models.CharField(default='Quality Control', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='step_4_title_ru',
            field=models.CharField(default='Quality Control', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='renovationinfo',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='renovationinfo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='renovationinfo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='renovationinfo',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renovationinfo',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renovationinfo',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
