# Generated by Django 5.1.3 on 2025-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_about_description_az_about_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefeaturevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='corefeaturevideo',
            name='thumbnail_az',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='corefeaturevideo',
            name='thumbnail_en',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='corefeaturevideo',
            name='thumbnail_ru',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
