# Generated by Django 5.1.3 on 2025-01-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_aboutsection_whats_in_it_for_me_points_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_home',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_home_az',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_home_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_home_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_title_az',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='breadcrumb_title_ru',
        ),
    ]
