# Generated by Django 5.1.3 on 2025-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_remove_aboutus_breadcrumb_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='whats_in_it_for_me_points_az',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='whats_in_it_for_me_points_en',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='whats_in_it_for_me_points_ru',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home',
            field=models.CharField(default='Home', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home_az',
            field=models.CharField(default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home_en',
            field=models.CharField(default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_home_ru',
            field=models.CharField(default='Home', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title',
            field=models.CharField(default='About Us', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title_az',
            field=models.CharField(default='About Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title_en',
            field=models.CharField(default='About Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='breadcrumb_title_ru',
            field=models.CharField(default='About Us', max_length=255, null=True),
        ),
    ]
